### PR TITLE
Update for socket.io v1.0

### PR DESCRIPTION
**Pull request by calebboyd**
Followed pattern set forth by this adapter: [socket.io-redis](https://github.com/Automattic/socket.io-redis)

### CODE REVIEW

**Comment by glennblock** [comment]
Hi @calebboyd if you want to send this over here, I've forked it. https://github.com/Azure-contrib/socket.io-servicebus

**Comment by calebboyd** [comment]
@glennblock sure thing!

**Comment by glennblock** [comment]
Hi @calebboyd 

Thanks! Not to be difficult but I am working to get this just transferred over to contrib in which case I'll delete my fork. If that happens, you'll need send another PR :-), also most likely to a diff branch.

I'll keep you posted in the next few days!

Glenn

**Comment by glennblock** [comment]
Thanks @calebboyd, we'll look into this now that we're in business.

**Comment by glennblock** [comment]
@calebboyd does this support synchronizing the list of clients? Redis has a DB and does Pub Sub on top. Service Bus is purely message based. When we were implementing the SB Store, we had to handle this by sending messages between to synchronize the lists.

**Comment by glennblock** [comment]
@calebboyd that was an issue with the chat sample app, not with the store itself.

On that note, did you look at the samples? Those are currently going to break if this PR is accepted. We need the samples to work.

**Comment by calebboyd** [comment]
Yeah I can take a look at those. Also it looks like a client api was added for cross node client handling in the [redis adapter](https://github.com/Automattic/socket.io-redis/blob/master/index.js#L150) . That will need to be looked at too. I've actually stopped using this in production (worked great when it was there), since azure added redis.

**Comment by glennblock** [comment]
Glad to hear it worked well for you. Understood on redis.

I appreciate your effort here and your patience!

**Comment by shijuvar** [comment]
This is really good thing that some updates are happening on this repository.

**Comment by glennblock** [comment]
An on that note...I just realized Travis CI needs to get fixed.

**Pull request closed without merging**
